stages:
  - test
  - sonarqube

code_quality:
  stage: test
  image: registry.gitlab.com/gitlab-org/ci-cd/codequality:latest
  script:
    - /codequality
  allow_failure: false
  artifacts:
    reports:
      codequality: gl-code-quality-report.json

sonarqube:
  stage: sonarqube
  image: sonarsource/sonar-scanner-cli
  before_script:
    - curl -Lo jq https://github.com/stedolan/jq/releases/latest/download/jq-linux64
    - chmod +x jq
    - export PATH=$PWD:$PATH

  script:
    - sonar-scanner -Dsonar.token="$SONAR_TOKEN"

    # Fetch SonarQube issues
    - |
      RESPONSE=$(curl -s "https://sonarcloud.io/api/issues/search?componentKeys=OveRide-Phoenix_kk_v1")
      echo "SonarQube Response: $RESPONSE"
      SONAR_ISSUES=$(echo "$RESPONSE" | jq '.total')
      echo "Total SonarQube Issues: $SONAR_ISSUES"

      if [ "$SONAR_ISSUES" -gt 0 ]; then
        MR_RESPONSE=$(curl -s --header "PRIVATE-TOKEN: $GITLAB_TOKEN" \
          "https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/merge_requests")

        echo "Merge Request Response: $MR_RESPONSE"

        # Determine if the response is an array or object
        if echo "$MR_RESPONSE" | jq -e 'if type == "array" then .[0].author.username else .author.username end' > /dev/null 2>&1; then
          MR_AUTHOR=$(echo "$MR_RESPONSE" | jq -r 'if type == "array" then .[0].author.username else .author.username end')
        else
          MR_AUTHOR="unknown"
        fi

        echo "MR Author: $MR_AUTHOR"

        # Loop through all issues and create separate GitLab issues
        echo "$RESPONSE" | jq -c '.issues[]' | while read issue; do
          ISSUE_TITLE=$(echo "$issue" | jq -r '.message')
          ISSUE_COMPONENT=$(echo "$issue" | jq -r '.component')
          ISSUE_LINE=$(echo "$issue" | jq -r '.line // "unknown"')

          curl --request POST --header "PRIVATE-TOKEN: $GITLAB_TOKEN" \
            --header "Content-Type: application/json" \
            --data "{
              \"title\": \"SonarQube Issue: $ISSUE_TITLE\",
              \"description\": \"Issue in $ISSUE_COMPONENT at line $ISSUE_LINE.\",
              \"assignee_ids\": [\"$MR_AUTHOR\"]
            }" \
            "https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/issues"

        done
      fi
  allow_failure: true
