stages:
  - test
  - sonarqube

code_quality:
  stage: test
  image: registry.gitlab.com/gitlab-org/ci-cd/codequality:latest
  script:
    - /codequality
  allow_failure: false
  artifacts:
    reports:
      codequality: gl-code-quality-report.json

sonarqube:
  stage: sonarqube
  image: sonarsource/sonar-scanner-cli
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
    GIT_DEPTH: 0  # Important for proper Git context
    SONAR_GITLAB_PROJECT_ID: ${CI_PROJECT_ID}
    SONAR_GITLAB_REF_NAME: ${CI_MERGE_REQUEST_SOURCE_BRANCH}
    SONAR_GITLAB_REF_TYPE: ${CI_MERGE_REQUEST_REF_TYPE}
    SONAR_GITLAB_MERGE_REQUEST_IID: ${CI_MERGE_REQUEST_IID}
    SONAR_GITLAB_MERGE_REQUEST_TARGET_BRANCH: ${CI_MERGE_REQUEST_TARGET_BRANCH}
  before_script:
    - curl -Lo jq https://github.com/stedolan/jq/releases/latest/download/jq-linux64
    - chmod +x jq
    - export PATH=$PWD:$PATH
  script:
    - sonar-scanner -Dsonar.projectKey="OveRide-Phoenix_kk_v1" -Dsonar.organization="overide-phoenix" -Dsonar.token="ed9e846a1947052b39fde8b0d9a535ee976de71e"
    - |
      RESPONSE=$(curl -s "https://sonarcloud.io/api/issues/search?componentKeys=OveRide-Phoenix_kk_v1")
      echo "SonarQube Response: $RESPONSE"
      SONAR_ISSUES=$(echo "$RESPONSE" | jq '.total')
      echo "Total SonarQube Issues: $SONAR_ISSUES"

      if [ "$SONAR_ISSUES" -gt 0 ]; then
        if [ -z "$GITLAB_TOKEN" ]; then
          echo "Error: GITLAB_TOKEN is not set"
          exit 1
        fi

        MR_RESPONSE=$(curl -s --header "PRIVATE-TOKEN: $GITLAB_TOKEN" \
          "https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/merge_requests")

        echo "Merge Request Response: $MR_RESPONSE"

        if echo "$MR_RESPONSE" | jq -e 'if type == "array" then .[0].author.username else .author.username end' > /dev/null 2>&1; then
          MR_AUTHOR=$(echo "$MR_RESPONSE" | jq -r 'if type == "array" then .[0].author.username else .author.username end')
        else
          MR_AUTHOR="unknown"
        fi

        echo "MR Author: $MR_AUTHOR"

        echo "$RESPONSE" | jq -c '.issues[]' | while read issue; do
          ISSUE_TITLE=$(echo "$issue" | jq -r '.message')
          ISSUE_COMPONENT=$(echo "$issue" | jq -r '.component')
          ISSUE_SEVERITY=$(echo "$issue" | jq -r '.severity')
          ISSUE_TYPE=$(echo "$issue" | jq -r '.type')
          ISSUE_LINE=$(echo "$issue" | jq -r '.line // "unknown"')
          ISSUE_RULE=$(echo "$issue" | jq -r '.rule')

          # Check if issue already exists in GitLab
          EXISTING_ISSUE=$(curl -s --header "PRIVATE-TOKEN: $GITLAB_TOKEN" \
            "https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/issues" | jq -r \
            --arg TITLE "$ISSUE_TITLE" '.[] | select(.title == $TITLE)')

          if [ -z "$EXISTING_ISSUE" ]; then
            echo "Creating new GitLab issue for: $ISSUE_TITLE"

            curl --request POST --header "PRIVATE-TOKEN: $GITLAB_TOKEN" \
              --header "Content-Type: application/json" \
              --data "{
                \"title\": \"SonarQube Issue: $ISSUE_TITLE\",
                \"description\": \"### SonarQube Issue Found\n
                **🔹 Severity:** $ISSUE_SEVERITY  \n
                **🔹 Type:** $ISSUE_TYPE  \n
                **🔹 Rule:** $ISSUE_RULE  \n
                **🔹 Component:** $ISSUE_COMPONENT  \n
                **🔹 Line:** $ISSUE_LINE  \n
                _This issue was detected automatically by SonarQube._\",
                \"assignee_ids\": [\"$MR_AUTHOR\"]
              }" \
              "https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/issues"
          else
            echo "Issue already exists in GitLab: $ISSUE_TITLE"
          fi
        done
      fi
  allow_failure: true
  only:
    - merge_requests
  rules:
    - if: $CI_MERGE_REQUEST_IID
      when: always
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: never
