code_quality:
  stage: test
  image: registry.gitlab.com/gitlab-org/ci-cd/codequality:latest
  script:
    - /codequality
  allow_failure: false  # Make pipeline fail if issues are found
  artifacts:
    reports:
      codequality: gl-code-quality-report.json
