CREATE TABLE IF NOT EXISTS delivery_routes (
  route_id INT NOT NULL AUTO_INCREMENT,
  city_code VARCHAR(10) NOT NULL,
  route_code VARCHAR(50) NOT NULL,
  route_name VARCHAR(150) NOT NULL,
  notes TEXT NULL,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  sort_order INT NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (route_id),
  UNIQUE KEY uq_delivery_routes_city_route_code (city_code, route_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
