CREATE TABLE Users (
    UserID INT PRIMARY KEY AUTO_INCREMENT,
    PhoneNumber VARCHAR(15) UNIQUE NOT NULL,
    Name VARCHAR(100),
    Email VARCHAR(100)
);

CREATE TABLE Address (
    AddressID INT PRIMARY KEY AUTO_INCREMENT,
    UserID INT,
    Latitude DECIMAL(10,7),
    Longitude DECIMAL(10,7),
    Area VARCHAR(255),
    AddressType VARCHAR(50),
    WrittenAddress TEXT,
    FOREIGN KEY (UserID) REFERENCES Users(UserID) ON DELETE CASCADE
);

CREATE TABLE Items (
    ItemID INT PRIMARY KEY AUTO_INCREMENT,
    Name VARCHAR(255) NOT NULL,
    Description TEXT,
    Price DECIMAL(10,2) NOT NULL,
    IsCombo BOOLEAN DEFAULT FALSE,
    ComboItems JSON
);

CREATE TABLE Menu (
    MenuID INT PRIMARY KEY AUTO_INCREMENT,
    Date DATE NOT NULL
);

CREATE TABLE Menu_Items (
    MenuItemID INT PRIMARY KEY AUTO_INCREMENT,
    MenuID INT,
    ItemID INT,
    Availability BOOLEAN DEFAULT TRUE,
    FOREIGN KEY (MenuID) REFERENCES Menu(MenuID) ON DELETE CASCADE,
    FOREIGN KEY (ItemID) REFERENCES Items(ItemID) ON DELETE CASCADE
);

CREATE TABLE Orders (
    OrderID INT PRIMARY KEY AUTO_INCREMENT,
    UserID INT,
    AddressID INT,
    OrderTime TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Status VARCHAR(50) CHECK (Status IN ('Pending', 'Completed', 'Cancelled')),
    FOREIGN KEY (UserID) REFERENCES Users(UserID) ON DELETE CASCADE,
    FOREIGN KEY (AddressID) REFERENCES Address(AddressID) ON DELETE SET NULL
);

CREATE TABLE Order_Items (
    OrderItemID INT PRIMARY KEY AUTO_INCREMENT,
    OrderID INT,
    ItemID INT,
    Quantity INT NOT NULL,
    Price DECIMAL(10,2) NOT NULL,
    FOREIGN KEY (OrderID) REFERENCES Orders(OrderID) ON DELETE CASCADE,
    FOREIGN KEY (ItemID) REFERENCES Items(ItemID) ON DELETE CASCADE
);
