import { GeistSans } from 'geist/font/sans'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <div className={GeistSans.className}>
      {children}
    </div>
  )
}
